apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastauth
  namespace: authentification
  labels:
    app: authentification
spec:
  selector:
    matchLabels:
      app: fastauth
  template:
    metadata:
      namespace: authentification
      labels:
        app: fastauth
    spec:
      containers:
        - name: fastauth
          image: GITHUB_REGISTRY_URL/fastauth:GITHUB_IMAGE_LABEL
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fastauth-secret
                  key: jwt_secret_key 

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: fastauth-secret
                  key: db_user 

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastauth-secret
                  key: db_password 

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: fastauth-configmap
                  key: db_host

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: fastauth-configmap
                  key: db_name

      imagePullSecrets:
        - name: GITHUB_PULL_SECRET_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: fastauth-service
  namespace: authentification
  labels:
    app: fastauth
spec:
  selector:
    app: fastauth
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
