name: Docker Build and Push, Kubernetes deploy

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
  
      - name: Docker Private Registry Login
        uses: docker/login-action@v1.14.1
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY_URL }}
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}

      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig 
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Build Docker Image
        run: |
          docker build --tag ${{ secrets.PRIVATE_REGISTRY_PREFIX }}/go_example:${{ github.sha }} .
          docker push ${{ secrets.PRIVATE_REGISTRY_PREFIX }}/go_example:${{ github.sha }}
          sed -i'' -e 's/REGISTRY_PREFIX/${{ secrets.PRIVATE_REGISTRY_PREFIX }}/g' -e 's/IMAGE_LABEL/${{ github.sha }}/g' k3s.yaml
          kubectl apply -f k3s.yaml
